<h4>Asignar o Denegar Permisos a Los Roles</h4>

<?php //if ($this->_acl->acceso('INSERT_PERMISO', false)): ?>
<form name="frmRol" method="post" action="<?php echo BASE_URL . Hash::urlEncrypt('administrador/permiRol/roles/1'); ?>" role="form" class="form-inline">
    <input type="hidden" value="1" name="enviar"/>
    Roles:
    <br/><br/>
    <div class="form-group">
		<?php if (isset($this->ddlRoles) && count($this->ddlRoles)): ?>
			<select name="ddlRoles" class="form-control">
				<option value="0">Seleccione...</option>
				<?php
				for ($i = 0; $i < $this->ddlRoles['numRows']; $i++):
					if (isset($this->datos['ddlRoles']) &&
							$this->datos['ddlRoles'] == $this->ddlRoles['ROL_ID'][$i]):
						?>
						<option value="<?php echo $this->ddlRoles['ROL_ID'][$i]; ?>" selected>
							<?php echo mb_convert_case($this->ddlRoles['ROL_DESCRIPCION'][$i], MB_CASE_TITLE, "utf8"); ?>
						</option>
						<?php
					else:
						?>
						<option value="<?php echo $this->ddlRoles['ROL_ID'][$i]; ?>">
							<?php echo mb_convert_case($this->ddlRoles['ROL_DESCRIPCION'][$i], MB_CASE_TITLE, "utf8"); ?>
						</option>
					<?php
					endif;
				endfor;
				?>
			</select>
		<?php else: ?>
			<strong>No se encontraron elementos!!!</strong>
		<?php endif; ?>
    </div>
    <button type="submit" value="Cargar" class="btn btn-search glyphicon glyphicon-search"></button>
</form>
<?php //endif; ?>
<br/>
<?php if (isset($this->permisos) && $this->permisos['numRows'] > 0): ?>
	<form class="frmPaginador" name="frmIPermiso" method="post">
		<input type="hidden" name="hidRol" value="<?php echo $this->rol; ?>"/>
		<input type="hidden" name="enviar" value="2"/>
		<table>
			<tr>
				<td>
					Llave:
					<input type="tex" name="txtFLlave" value="<?php if (isset($this->filtros['txtFLlave'])) echo $this->filtros['txtFLlave']; ?>"/>
				</td>
				<td colspan="2">
					Detalles:
					<input type="tex" name="txtFDetalle" value="<?php if (isset($this->filtros['txtFDetalle'])) echo $this->filtros['txtFDetalle']; ?>"/>
				</td>
				<td>
					<input type="submit"  name="btnFiltros" value="filtrar"/>
				</td>
			</tr>
			<tr>
				<td>
					Estado:
					<input type="tex" name="txtFEstado" value="<?php if (isset($this->filtros['txtFEstado'])) echo $this->filtros['txtFEstado']; ?>"/>
				</td>
				<td>
					Fecha Registro:
					<input type="tex" name="txtFFecha" value="<?php if (isset($this->filtros['txtFFecha'])) echo $this->filtros['txtFFecha']; ?>"/>
				</td>
				<td>
					Hora Registro:
					<input type="tex" name="txtFHora" value="<?php if (isset($this->filtros['txtFHora'])) echo $this->filtros['txtFHora']; ?>"/>
				</td>
				<td>
					<input type="submit" name="btnFiltros" value="limpiar"/>
				</td>
			</tr>
		</table>
		<table>
			<tr>
				<th>N°</th>
				<th>Llave</th>
				<th>Detalles</th>
				<th>Fecha Registro</th>
				<th>Hora Registro</th>
				<th>Estado</th>
			</tr>
			<?php for ($i = 0; $i < $this->permisos['numRows']; $i++): ?>
				<tr>
					<td>
						<?php echo ($this->actual + $i); ?>
						<input type="hidden" name="hidId[]" value="<?php echo $this->permisos['PERMISO_ID'][$i]; ?>"/>
					</td>
					<td><?php echo $this->permisos['PERMISO_KEY'][$i]; ?></td>
					<td><?php echo $this->permisos['PERMISO_DETALLE'][$i]; ?></td>
					<td><?php echo $this->permisos['EST_REG_FECHA_REGISTRO'][$i]; ?></td>
					<td><?php echo $this->permisos['EST_REG_HORA_REGISTRO'][$i]; ?></td>
					<?php
					if (key_exists('EST_REG_TIP_EST', $this->permRoles))
						$chk = $this->permRoles['EST_REG_TIP_EST'][$i];
					else
						$chk = 0;
					?>
					<td>
						<input type="checkbox" name="chkEstado[]" value="<?php echo $this->permisos['PERMISO_ID'][$i]; ?>" <?php echo ($chk == 1) ? 'checked' : ''; ?>/>
					</td>
				</tr>
			<?php endfor; ?>
			<tr>
				<td colspan="8">
					<div>
						<?php $ant = (($this->actual - 1) < 1) ? 1 : ($this->actual - 1); ?>
						<?php $sig = (($this->actual + 1) > $this->paginas) ? $this->paginas : ($this->actual + 1); ?>
						<a class="linkPaginador" href="<?php echo BASE_URL . Hash::urlEncrypt('administrador/permiRol/roles/1'); ?>"><<-</a>
						<a class="linkPaginador" href="<?php echo ('administrador/permiRol/roles/' . $ant); ?>"><-</a>
						<?php for ($i = 1; $i <= $this->paginas; $i++): ?>
							<?php if ($i == $this->actual): ?>
								<a style="background: #819FF7;"><?php echo $i; ?></a>
							<?php elseif ($i >= ($this->actual - 7) && $i <= ($this->actual + 7)): ?>
								<a class="linkPaginador" href="<?php echo BASE_URL . Hash::urlEncrypt('administrador/permiRol/roles/' . $i); ?>"><?php echo $i; ?></a>
							<?php else: ?>
								<?php if ($i == ($this->actual - 8) && ($this->actual - 8) != 1): ?>
									<a>...</a>
								<?php elseif ($i == ($this->actual + 8) && ($this->actual + 8) != $this->paginas): ?>
									<a>...</a>
								<?php endif; ?>
							<?php endif; ?>
						<?php endfor; ?>
						<a class="linkPaginador" href="<?php echo ('administrador/permiRol/roles/' . $sig); ?>">-></a>
						<a class="linkPaginador" href="<?php echo BASE_URL . Hash::urlEncrypt('administrador/permiRol/roles/' . $this->paginas); ?>">->></a>
					</div>
				</td>
			</tr>
		</table>
		<input type="submit" name="btnGuardar" value="Guardar"/>
	</form>
<?php endif; ?>
