<div class="contenido">
    <h4>
            Certificación de Competencias Laborales
    </h4>
    <br>
    <p>
            El Servicio Nacional de Aprendizaje SENA, mediante Decreto 249 de 2004 Articulo 12, es el responsable en Colombia de evaluar y certificar la competencia laboral de los colombianos; y a través del Decreto 933 de 2003 en su Artículo 19 Certificación de Competencias Laborales, es autorizado para Evaluar y Certificar la competencia Laboral, y dice textualmente: "El Servicio Nacional de Aprendizaje-SENA regulará, diseñará, normalizará y certificará las competencias laborales”. Este procedimiento se diseña a través dela Dirección del Sistema Nacional de Formación para el Trabajo DSNFT y se ejecuta en los Centros, tomando como base los esquemas de evaluación y certificación y normas de competencia laboral, insumo para que el sector productivo defina e implemente políticas y estrategias para el desarrollo y gestión del talento humano.
    </p>
    <p>
            Colombia adelanta la Evaluación y Certificación de las Competencias Laborales (ECCL) del talento humano del país, a partir de las normas de competencia laboral definidas por el sector productivo, mediante las Mesas Sectoriales. El SENA y otros Organismos Certificadores acreditados por el Organismo Nacional de Acreditación - ONAC, prestan en la actualidad el servicio de certificación de personas. Estos parámetros nacionales, son una herramienta para la valoración de las competencias de los trabajadores, que incluye la demostración de evidencias de conocimiento, producto y desempeño por parte de los candidatos sin importar cómo ni cuándo éstos se hayan adquirido. Así mismo, facilitan la medición, mejoramiento de la calidad, productividad de las empresas y de conglomerados de empresas, cadenas productivas, sectores y regiones.
    </p>
</div>