<h4>
    Principios de la Evaluación y la Certificación de la Competencia Laboral-ECCL 
</h4>
<br>
<p>
    La evaluación y certificación de la competencia laboral (ECCL) se soporta en cuatro principios fundamentales:
</p>
<dt>
Equidad:
</dt>
<p>
    Es accesible a toda persona, evitando toda práctica discriminatoria, barreras o restricciones, teniendo en cuenta el cumplimiento de los requisitos de ingreso establecidos en esta guía y los definidos en los Esquemas de Evaluación y Certificación de Competencias Laborales (ECCL). 
</p>

<dt>
Imparcialidad:
</dt>
<p>
    Está basado en las evidencias requeridas por la Norma de Competencia Laboral (NCL) y en los resultados de evaluación a partir de instrumentos válidos y confiables, garantizando la objetividad y transparencia en el procedimiento. 
</p>
<dt>
Excelencia:
</dt>
<p>
    Es el cumplimiento del 100% en cada una de las evidencias exigidas en la Norma de Competencia Laboral que demuestra el candidato para poder ostentar que es COMPETENTE. 
</p>
<dt>
Transparencia:
</dt>
<p>
    La información del proceso es clara, precisa y concreta y está disponible para los diferentes actores. 
</p>
<br>
<h4>
    Características de la Evaluación y Certificación de Competencias Laborales-ECCL
</h4>
<br>
<dt>
Gratuito:
</dt>
<p>
    Se fundamenta en que para el candidato no representa pagos en dinero, especie, directos e indirectos al SENA o a las empresas, independientemente de la línea de atención que se establezca (Alianza o Demanda Social). 
</p>
<dt>
Accesible:
</dt>
<p>
    Se accede de forma voluntaria a la Evaluación y Certificación de la Competencia Laboral de manera libre y espontánea y no por obligación o deber, teniendo en cuenta que el candidato es quien decide en qué momento puede demostrar las evidencias de desempeño y producto requeridas por la Norma de Competencia Laboral (NCL) a certificar. Las evidencias de conocimiento son programadas por el SENA, previa concertación, aún en los casos de obligatoriedad legal o por política institucional como es el caso de funciones productivas que revisten alto riesgo para la comunidad o que constituyen un factor importante para la calidad en la prestación del servicio correspondiente. 
</p>
<dt>
Sistémico:
</dt>
<p>
    El procedimiento se ciñe a las fases, requisitos y condiciones establecidas en esta guía y en los Esquemas de Evaluación y Certificación de Competencias Laborales (ECCL).
</p>
<dt>
Legítimo:
</dt>
<p>
    Se define y establece por el Organismo Certificador SENA de manera auténtica y propia garantizando el cumplimiento de la normatividad interna y externa. Se suma a esta característica las evidencias presentadas por el candidato de manera individual a través de las cuales demuestra su autoría y propiedad, bajo un marco legal establecido.
</p>
<dt>
Práctico:
</dt>
<p>
    Se centra en la experiencia y experticia que debe demostrar un candidato sin importar la forma o manera de cómo, cuándo y dónde adquirió la competencia.
</p>

<dt>
Estandarizado:
</dt>
<p>
    Se basa en un modelo propio y de uso exclusivo del SENA a nivel nacional, soportado en Normas adoptadas, adaptadas o reconocidas por los sectores productivos y Esquemas de Evaluación y Certificación de Competencias Laborales. 
</p>
<dt>
Válido: 
</dt>
<p>
    Mide evidencias de conocimiento, desempeño y producto requeridos para el desempeño competente de una función productiva.
</p>
<dt>
Justo:
</dt>
<p>
    Brinda a todos y cada uno de los candidatos las mismas oportunidades en la valoración de evidencias y certificación. 
</p>
<dt>
Confiable: 
</dt>
<p>
    El proceso de evaluación mide consistentemente las evidencias que debe demostrar un candidato.
</p>
<dt>
Independiente:
</dt>
<p>
    Los actores que intervienen en el proceso no deben desempeñar más de un rol simultáneamente ni hacer parte de otro proceso. 
</p>