<h4>
    ¿Qué es la Evaluación de la Competencia Laboral? 
</h4>
<p>
    Es el proceso por medio del cual un evaluador recoge de una persona, evidencias de su desempeño, producto y conocimiento, con el fin de determinar si es competente, o aún no competente, para desempeñar una función productiva. La evaluación de la competencia laboral se centra en el desempeño real de las personas, soportado por evidencias válidas y confiables con base en el referente que es la norma de competencia laboral y no en potencialidades.
</p>
<br>
<h4>
    ¿Qué es la Certificación de la Competencia Laboral? 
</h4>
<p>
    Es el reconocimiento, por escrito, que hace un organismo certificador a una persona que cumple con los requisitos establecidos en una norma de competencia laboral, corroborándolo mediante evidencias de conocimiento, desempeño y producto.
</p>
<img src="<?php echo BASE_URL . 'public' . DS . 'img' . DS . 'imgquees.png'; ?>" class="img-thumbnail center-block"> 
<br>
<h4>
    ¿Quiénes Pueden Acceder al Servicio? 
</h4>
<p>
    Todo Colombiano o extranjero que resida en nuestro país mayor de 17 años de edad que sabe, conoce, maneja y ha desempeñado como mínimo veinti cuatro(24) meses de experiencia en un oficio, labor, función o actividad laboral y desea le sea reconocido por un Organismo Certificador su Competencia.
</p>
