<h4>Registrar Nuevo Usuario</h4>
<br>
<form name="frmRUsuario" method="post" action="" class="form-group  col-xs-3">
    <input type="hidden" value="1" name="enviar"/>

    <?php echo $ddlTDocumento = (isset($this->ddlTDocumento)) ? $this->ddlTDocumento : 'ddl No encontrado!!!'; ?>
    
    <label>Documento: </label>
    <input type="text" name="txtDocumento" value="<?php if (isset($this->datos['txtDocumento'])) echo $this->datos['txtDocumento']; ?>" class="form-control"/>

    <label>Lugar de Expedición: </label>
    <input type="text" name="txtLExpedicion" value="<?php if (isset($this->datos['txtLExpedicion'])) echo $this->datos['txtLExpedicion']; ?>" class="form-control"/>

    <label>Nombre: </label>
    <input type="text" name="txtNombre" value="<?php if (isset($this->datos['txtNombre'])) echo $this->datos['txtNombre']; ?>" class="form-control"/>

    <label>Primer Apellido: </label>
    <input type="text" name="txtPApellido" value="<?php if (isset($this->datos['txtPApellido'])) echo $this->datos['txtPApellido']; ?>" class="form-control"/>

    <label>Segundo Apellido: </label>
    <input type="text" name="txtSApellido" value="<?php if (isset($this->datos['txtSApellido'])) echo $this->datos['txtSApellido']; ?>" class="form-control"/>

    <label>Correo Electronico: </label>
    <input type="text" name="txtEmail" value="<?php if (isset($this->datos['txtEmail'])) echo $this->datos['txtEmail']; ?>" class="form-control"/>
    
    <?php echo $ddlPNacimiento = (isset($this->ddlPNacimiento)) ? $this->ddlPNacimiento : 'ddl No encontrado!!!'; ?> 

    <label>Fecha de Nacimiento: </label>
    <input type="text" name="txtFNacimiento" value="<?php if (isset($this->datos['txtFNacimiento'])) echo $this->datos['txtFNacimiento']; ?>" class="form-control"/>
    
    <?php echo $ddlNacionalidad = (isset($this->ddlNacionalidad)) ? $this->ddlNacionalidad : 'ddl No encontrado!!!'; ?> 
    
    <?php echo $ddlGenero = (isset($this->ddlGenero)) ? $this->ddlGenero : 'ddl No encontrado!!!'; ?> 
    
    <?php echo $ddlGSanguineo = (isset($this->ddlGSanguineo)) ? $this->ddlGSanguineo : 'ddl No encontrado!!!'; ?> 
    
    <?php echo $ddlECivil = (isset($this->ddlECivil)) ? $this->ddlECivil : 'ddl No encontrado!!!'; ?> 

    <label>Usuario: </label>
    <input type="text" name="txtNickName" value="<?php if (isset($this->datos['txtNickName'])) echo $this->datos['txtNickName']; ?>" class="form-control"/>

    <label>Contraseña: </label>
    <input type="password" name="txtPassword" class="form-control"/>
 
    <label>Repita la Contraseña: </label>
    <input type="password" name="txtConfirmar" class="form-control"/>

    <br>
    <input type="submit" value="Registrar" class="btn btn-warning center-block"/>
</form>