<!--    <div class="form-group">-->
<label><?php echo $nombreCampo?>: </label>
<?php if (isset($datos) && count($datos)): ?>
	<select name="ddlTDocumento" class="form-control input-sm">
		<option value="0">Seleccione...</option>
		<?php
		for ($i = 0; $i < $datos['numRows']; $i++):
			if (isset($this->datos['ddlTDocumento']) &&
					$this->datos['ddlTDocumento'] == $datos['TIP_DOCU_ID'][$i]):
				?>
				<option value="<?php echo $datos['TIP_DOCU_ID'][$i]; ?>" selected>
					<?php echo utf8_encode($datos['TIP_DOCU_NOMBRE'][$i]); ?>
				</option>
				<?php
			else:
				?>
				<option value="<?php echo $datos['TIP_DOCU_ID'][$i]; ?>">
					<?php echo utf8_encode($datos['TIP_DOCU_NOMBRE'][$i]); ?>
				</option>
			<?php
			endif;
		endfor;
		?>
	</select>
<?php else: ?>
	<strong>error!!!</strong>
<?php endif; ?>
<!--</div>-->