<ul id="menuPrincipal" class="ulMenuPrincipal">
	<?php if (isset($menu)): ?>
		<?php for ($i = 0; $i < count($menu); $i++): ?>
			<?php
			if ($item && $menu[$i]['id'] == $item)
			{
				$_item_style = 'current';
			}
			else
			{
				$_item_style = '';
			}
			?>        
			<li class="liPrin liPrin-<?php echo $i; ?>">
				<?php
				unset($url);
				unset($href);
				$url = (isset($menu[$i]['enlace'])) ? $menu[$i]['enlace'] : '';
				$href = (!empty($url)) ? 'href="' . $url . '"' : '';
				?>
				<a class="<?php echo $_item_style; ?>" <?php echo $href; ?>>
					<?php echo $menu[$i]['titulo']; ?>
				</a>	
				<?php if (isset($menu[$i]['submenu']) && $menu[$i]['submenu']): ?>
					<ul class="ulSubMenu oculto">
						<?php for ($j = 0; $j < count($menu[$i]['subArray']); $j++): ?>
							<?php
							if ($item && $menu[$i]['subArray'][$j]['id'] == $item)
							{
								$_item_style = 'current';
							}
							else
							{
								$_item_style = '';
							}
							?>        
							<li class="liSubMenu liSubMenu-<?php echo $j; ?>">
								<?php
								unset($url);
								unset($href);
								$url = (isset($menu[$i]['subArray'][$j]['enlace'])) ? $menu[$i]['subArray'][$j]['enlace'] : '';
								$href = (!empty($url)) ? 'href="' . $url . '"' : '';
								?>
								<a class="<?php echo $_item_style; ?> " <?php echo $href; ?>>
									<?php echo $menu[$i]['subArray'][$j]['titulo']; ?>
								</a>	
								<?php if (isset($menu[$i]['subArray'][$j]['submenu']) && $menu[$i]['subArray'][$j]['submenu']): ?>
									<ul class="ulSubMenu2 ulSubMenu2-<?php echo $j; ?> oculto">
										<?php for ($k = 0; $k < count($menu[$i]['subArray'][$j]['subArray']); $k++): ?>
											<?php
											if ($item && $menu[$i]['subArray'][$j]['subArray'][$k]['id'] == $item)
											{
												$_item_style = 'current';
											}
											else
											{
												$_item_style = '';
											}
											?>        
											<li class="liSubMenu2-<?php echo $k; ?>">
												<?php
												unset($url);
												unset($href);
												$url = (isset($menu[$i]['subArray'][$j]['subArray'][$k]['enlace'])) ? $menu[$i]['subArray'][$j]['subArray'][$k]['enlace'] : '';
												$href = (!empty($url)) ? 'href="' . $url . '"' : '';
												?>
												<a class="<?php echo $_item_style; ?> " <?php echo $href; ?>>
													<?php echo $menu[$i]['subArray'][$j]['subArray'][$k]['titulo']; ?>
												</a>
											</li>
										<?php endfor; ?>
									</ul>
								<?php endif; ?>
							</li>
						<?php endfor; ?>
					</ul>
				<?php endif; ?>
			</li>
		<?php endfor; ?>
	<?php endif; ?>
</ul>